config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "pages#index"

  get "login", to: "pages#show_login"
  post "login", to: "pages#new_login"
  get "logout", to: "pages#logout"

  resources :seat_classes
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seat.rb
class Seat < ApplicationRecord
        belongs_to :flight
        belongs_to :seat_class

        validate :check_capacity
        validate :check_baggage

        private

        def check_capacity
            seats = Seat.where(flight_id: flight_id).length
            capacity = Flight.find(flight_id).capacity

            if capacity <= seats then 
                    errors.add(:flight_id, "Flight is full")
            end
        end

        def check_baggage
            seats = Seat.where(flight_id: flight_id)
        
            sum_baggage = 0

            seats.each do |s|
                sum_baggage += s.baggage.to_f
            end

            ba = Flight.find(flight_id).baggage_allowance

            if sum_baggage + baggage > ba then      
                errors.add(:baggage, "Flight Baggage capacity exceeded by " + (-1*(ba - sum_baggage - baggage )).to_s)
            end
        end

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
      params.require(:seat).permit(:flight_id, :name, :baggage, :seat_class_id)
    end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.number_field :flight_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <%= form.collection_select(:seat_class_id, SeatClass.all, :id, :class_name) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/_seat_class_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seat Classes</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Price</th>
      <th>Food service</th>
      <th>Seat type</th>
      <th>Leg room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% seat_classes.each do |seat_class| %>
      <tr>
        <td><%= seat_class.class_name %></td>
        <td>$<%= seat_class.price %></td>
        <td><%= seat_class.food_service %></td>
        <td><%= seat_class.seat_type %></td>
        <td><%= seat_class.leg_room %> inches</td>
        <td><%= link_to 'Show', seat_class %></td>
        <td><%= link_to 'Edit', edit_seat_class_path(seat_class) %></td>
        <td><%= link_to 'Destroy', seat_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat Class', new_seat_class_path %>

app/views/seats/_seat_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %> |
<%= link_to 'Back to Flights', flights_path %>

app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<%= render "shared/jumbotron", header: "Seats", tag_line: "List of all Seats taken", alignment: "text-left"%>
<%= render "seat_list", seats: @seats %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>
<%= render 'seat_class_index', seat_classes: SeatClass.all%>


|| <%= link_to 'Back to seats', seats_path %> ||
<%= link_to 'Back to flights', flights_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight:</strong>
  <%= @seat.flight_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @seat.name %>
</p>

<p>
  <strong>Baggage:</strong>
  <%= @seat.baggage %>
</p>

<p>
  <strong>Seat Class: </strong>
  <%= @seat_classes %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>