config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "pages#index"

  get "login", to: "pages#show_login"
  post "login", to: "pages#new_login"
  get "logout", to: "pages#logout"

  resources :seat_classes
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
    
    #dependent destroy when a flight is destroyed then the seats are also destroyed
    has_many :seats, dependent: :destroy
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    @open_flights = []
    @closed_flights = []

    @flights.each do |f|   
      if f.seats.length >= f.capacity then
            @closed_flights.append(f)
      else
            @open_flights.append(f)
      end
    
    end
    @result = Seat.all.group(:seat_class_id).count

    @chart_data = {}

    @result.each do |k, v|
      @chart_data[SeatClass.find(k).class_name] = v
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    Leaflet.tile_layer = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.pngrai"
    # You can also use any other tile layer here if you don't want to use Cloudmade - see http://leafletjs.com/reference.html#tilelayer for more
    Leaflet.attribution = "Your attribution statement"
    Leaflet.max_zoom = 18
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:departure, :arrival, :destination, :baggage_allowance, :capacity)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :baggage_allowance %>
    <%= form.text_field :baggage_allowance %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_list_flight.html.erb
<p id="notice"><%= notice %></p>

<h1><%= header %></h1>

<table class="table table-dark table-borderless">
  <thead>
    <tr>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Destination</th>
      <th>Baggage allowance</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% flights.each do |flight| %>
      <tr>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.baggage_allowance %></td>
        <td><%= flight.capacity%></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if header == "Open Flights"%>
<%= link_to 'New Flight', new_flight_path %>
<% end %>

app/views/flights/_seat_class_index.html.erb
<p id="notice"><%= notice %></p>

<h1> Here is the list of all Seat Classes: </h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Price</th>
      <th>Food service</th>
      <th>Seat type</th>
      <th>Leg room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% seat_classes.each do |seat_class| %>
      <tr>
        <td><%= seat_class.class_name %></td>
        <td>$<%= seat_class.price %></td>
        <td><%= seat_class.food_service %></td>
        <td><%= seat_class.seat_type %></td>
        <td><%= seat_class.leg_room %> inches</td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/_seat_form.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :flight_id, value: flight_id %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <%= form.collection_select(:seat_class_id, SeatClass.all, :id, :class_name) %>
    
  <div class="actions">
    <%= form.submit %>
  </div>



<% end %>

app/views/flights/_seat_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th>Seat Class</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
	      <td><%= seat.seat_class.class_name %></td>       
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if flight.seats.length < flight.capacity then %>
  <%= link_to 'New Seat', new_seat_path %>\
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<%= render "shared/jumbotron", header: "Flight Information", tag_line: "...", alignment: "text-center"%>

<%= pie_chart @chart_data %>

<%= render "list_flight", flights: @open_flights, header: "Open Flights"%>
<%= render "list_flight", flights: @closed_flights, header: "Closed Flights"%>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>


<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<%= map(:center => {
  :latlng => [51.52238797921441, -0.08366235665359283],
  :zoom => 18
}) %>

<p id="notice"><%= notice %></p>


<h1>Flights</h1>
<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Baggage allowance:</strong>
  <%= @flight.baggage_allowance %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @flight.capacity %>
</p>

 <% #render "name of partial", local_variable: database_finder %>                    
<%= render 'seat_index', seats: @flight.seats, flight: @flight %>

<% if @flight.seats.length < @flight.capacity then %>
    <%= render 'seat_form', seat: Seat.new, flight_id: @flight.id %>
<% else %>
    FLIGHT IS FULL
<% end %>
<br>
<%= link_to 'Back', flights_path %>