config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "pages#index"

  get "login", to: "pages#show_login"
  post "login", to: "pages#new_login"
  get "logout", to: "pages#logout"

  resources :seat_classes
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/seat_classes_controller.rb
class SeatClassesController < ApplicationController
  before_action :set_seat_class, only: [:show, :edit, :update, :destroy]

  # GET /seat_classes
  # GET /seat_classes.json
  def index
    @seat_classes = SeatClass.all
  end

  # GET /seat_classes/1
  # GET /seat_classes/1.json
  def show
  end

  # GET /seat_classes/new
  def new
    @seat_class = SeatClass.new
  end

  # GET /seat_classes/1/edit
  def edit
  end

  # POST /seat_classes
  # POST /seat_classes.json
  def create
    @seat_class = SeatClass.new(seat_class_params)

    respond_to do |format|
      if @seat_class.save
        format.html { redirect_to @seat_class, notice: 'Seat class was successfully created.' }
        format.json { render :show, status: :created, location: @seat_class }
      else
        format.html { render :new }
        format.json { render json: @seat_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seat_classes/1
  # PATCH/PUT /seat_classes/1.json
  def update
    respond_to do |format|
      if @seat_class.update(seat_class_params)
        format.html { redirect_to @seat_class, notice: 'Seat class was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat_class }
      else
        format.html { render :edit }
        format.json { render json: @seat_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seat_classes/1
  # DELETE /seat_classes/1.json
  def destroy
    @seat_class.destroy
    respond_to do |format|
      format.html { redirect_to seat_classes_url, notice: 'Seat class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat_class
      @seat_class = SeatClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_class_params
      params.require(:seat_class).permit(:class_name, :price, :food_service, :seat_type, :leg_room)
    end
end

app/helpers/seat_classes_helper.rb
module SeatClassesHelper
end

app/views/seat_classes/_form.html.erb
<div class="card mx-auto mt-3" style="width: 30%">
  <div class="card-header  bg-secondary text-light"><h1>New Seat Class</h1></div>
  <div class="card-body  bg-secondary text-light">
  <%= form_with(model: seat_class, local: true) do |form| %>
    <% if seat_class.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(seat_class.errors.count, "error") %> prohibited this seat_class from being saved:</h2>

        <ul>
        <% seat_class.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :class_name %>
      <%= form.text_field :class_name %>
    </div>

    <div class="field">
      <%= form.label :price %>
      $<%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :food_service %>
      <%= form.check_box :food_service %>
    </div>

    <div class="field">
      <%= form.label :seat_type %>
      <%= form.text_field :seat_type %>
    </div>

    <div class="field">
      <%= form.label :leg_room %>
      <%= form.number_field :leg_room %> inches
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/seat_classes/edit.html.erb
<h1>Editing Seat Class</h1>

<%= render 'form', seat_class: @seat_class %>

<%= link_to 'Show', @seat_class %> |
<%= link_to 'Back', seat_classes_path %>

app/views/seat_classes/index.html.erb
<%= render "shared/jumbotron", header: "Seat Classes", tag_line: "Seat Class Information", alignment: "text-center"%>

<h1>Types of Seats</h1>

<table class="table table-dark table-borderless">
  <thead>
    <tr>
      <th>Class name</th>
      <th>Price</th>
      <th>Food service</th>
      <th>Seat type</th>
      <th>Leg room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seat_classes.each do |seat_class| %>
      <tr>
        <td><%= seat_class.class_name %></td>
        <td>$<%= seat_class.price %></td>
        <td><%= seat_class.food_service %></td>
        <td><%= seat_class.seat_type %></td>
        <td><%= seat_class.leg_room %> inches</td>
        <td><%= link_to 'Show', seat_class %></td>
        <td><%= link_to 'Edit', edit_seat_class_path(seat_class) %></td>
        <td><%= link_to 'Destroy', seat_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat Class', new_seat_class_path %>

app/views/seat_classes/new.html.erb
<h1>New Seat Class</h1>

<%= render 'form', seat_class: @seat_class %>

<%= link_to 'Back', seat_classes_path %>

app/views/seat_classes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mx-auto mt-3" style="width: 30%">
  <div class="card-header  bg-secondary text-light">Seat Information
  </div>
  <div class="card-body">
    <div>
      <strong>Class name:</strong>
      <%= @seat_class.class_name %>
    </div>

    <div>
      <strong>Price: </strong>
      <%= @seat_class.price %>
    </div>

    <div>
      <strong>Food service:</strong>
      <%= @seat_class.food_service %>
    </div>

    <div>
      <strong>Seat type:</strong>
      <%= @seat_class.seat_type %>
    </div>

    <div>
      <strong>Leg room:</strong>
      <%= @seat_class.leg_room %>
    </div>
  </div>
<%= link_to 'Edit', edit_seat_class_path(@seat_class) %>
<%= link_to 'Back', seat_classes_path %>
</div>